In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
dir_data = './data_Day6'
f_app_train = os.path.join(dir_data, 'application_train.csv')
f_app_test = os.path.join(dir_data, 'application_test.csv')

app_train = pd.read_csv(f_app_train)
app_test = pd.read_csv(f_app_test)

In [3]:
app_train.dtypes.value_counts()

float64    65
int64      41
object     16
dtype: int64

In [4]:
app_train.select_dtypes(include=['object']).apply(pd.Series.nunique, axis = 0)

NAME_CONTRACT_TYPE             2
CODE_GENDER                    3
FLAG_OWN_CAR                   2
FLAG_OWN_REALTY                2
NAME_TYPE_SUITE                7
NAME_INCOME_TYPE               8
NAME_EDUCATION_TYPE            5
NAME_FAMILY_STATUS             6
NAME_HOUSING_TYPE              6
OCCUPATION_TYPE               18
WEEKDAY_APPR_PROCESS_START     7
ORGANIZATION_TYPE             58
FONDKAPREMONT_MODE             4
HOUSETYPE_MODE                 3
WALLSMATERIAL_MODE             7
EMERGENCYSTATE_MODE            2
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()
le_count = 0

for col in app_train:
    if app_train[col].dtype == 'object':
        if len(list(app_train[col].unique()))<=2:
            le.fit(app_train[col])
            app_train[col] = le.transform(app_train[col])
            app_test[col] = le.transform(app_test[col])
            le_count += 1

print('%d columns were label encoded.' % le_count)

3 columns were label encoded.

In [7]:
app_train = pd.get_dummies(app_train)
app_test = pd.get_dummies(app_test)

print(app_train['CODE_GENDER_F'].head())
print(app_train['CODE_GENDER_M'].head())
print(app_train['NAME_EDUCATION_TYPE_Academic degree'].head())

0    0
1    1
2    0
3    1
4    0
Name: CODE_GENDER_F, dtype: uint8
0    1
1    0
2    1
3    0
4    1
Name: CODE_GENDER_M, dtype: uint8
0    0
1    0
2    0
3    0
4    0
Name: NAME_EDUCATION_TYPE_Academic degree, dtype: uint8

In [10]:
app_train = pd.read_csv(f_app_train)
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head()

(307511, 1)

  WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [12]:
sub_train1 = pd.get_dummies(sub_train)
print(sub_train1.shape)
print(sub_train1)

(307511, 7)
        WEEKDAY_APPR_PROCESS_START_FRIDAY  WEEKDAY_APPR_PROCESS_START_MONDAY  \
0                                       0                                  0
1                                       0                                  1
2                                       0                                  1
3                                       0                                  0
4                                       0                                  0
5                                       0                                  0
6                                       0                                  0
7                                       0                                  1
8                                       0                                  0
9                                       0                                  0
10                                      0                                  0
11                                      1                                  0
12                                      1                                  0
13                                      0                                  0
14                                      0                                  1
15                                      0                                  0
16                                      0                                  0
17                                      0                                  1
18                                      1                                  0
19                                      0                                  1
20                                      1                                  0
21                                      0                                  1
22                                      0                                  0
23                                      1                                  0
24                                      0                                  0
25                                      0                                  0
26                                      0                                  1
27                                      0                                  0
28                                      0                                  0
29                                      0                                  0
...                                   ...                                ...
307481                                  1                                  0
307482                                  0                                  0
307483                                  0                                  1
307484                                  0                                  1
307485                                  0                                  0
307486                                  0                                  0
307487                                  0                                  0
307488                                  0                                  0
307489                                  1                                  0
307490                                  0                                  0
307491                                  0                                  0
307492                                  1                                  0
307493                                  0                                  1
307494                                  0                                  1
307495                                  0                                  0
307496                                  0                                  0
307497                                  0                                  0
307498                                  0                                  1
307499                                  0                                  0
307500                                  1                                  0
307501                                  0                                  0
307502                                  0                                  1
307503                                  0                                  0
307504                                  0                                  0
307505                                  0                                  1
307506                                  0                                  0
307507                                  0                                  1
307508                                  0                                  0
307509                                  0                                  0
307510                                  0                                  0

        WEEKDAY_APPR_PROCESS_START_SATURDAY  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0
5                                         0
6                                         0
7                                         0
8                                         0
9                                         0
10                                        1
11                                        0
12                                        0
13                                        0
14                                        0
15                                        1
16                                        0
17                                        0
18                                        0
19                                        0
20                                        0
21                                        0
22                                        0
23                                        0
24                                        0
25                                        1
26                                        0
27                                        1
28                                        0
29                                        0
...                                     ...
307481                                    0
307482                                    0
307483                                    0
307484                                    0
307485                                    1
307486                                    1
307487                                    0
307488                                    0
307489                                    0
307490                                    1
307491                                    1
307492                                    0
307493                                    0
307494                                    0
307495                                    0
307496                                    0
307497                                    0
307498                                    0
307499                                    0
307500                                    0
307501                                    0
307502                                    0
307503                                    1
307504                                    0
307505                                    0
307506                                    0
307507                                    0
307508                                    0
307509                                    0
307510                                    0

        WEEKDAY_APPR_PROCESS_START_SUNDAY  \
0                                       0
1                                       0
2                                       0
3                                       0
4                                       0
5                                       0
6                                       1
7                                       0
8                                       0
9                                       0
10                                      0
11                                      0
12                                      0
13                                      0
14                                      0
15                                      0
16                                      0
17                                      0
18                                      0
19                                      0
20                                      0
21                                      0
22                                      0
23                                      0
24                                      0
25                                      0
26                                      0
27                                      0
28                                      0
29                                      0
...                                   ...
307481                                  0
307482                                  0
307483                                  0
307484                                  0
307485                                  0
307486                                  0
307487                                  0
307488                                  0
307489                                  0
307490                                  0
307491                                  0
307492                                  0
307493                                  0
307494                                  0
307495                                  0
307496                                  0
307497                                  0
307498                                  0
307499                                  0
307500                                  0
307501                                  0
307502                                  0
307503                                  0
307504                                  0
307505                                  0
307506                                  0
307507                                  0
307508                                  0
307509                                  0
307510                                  0

        WEEKDAY_APPR_PROCESS_START_THURSDAY  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         1
5                                         0
6                                         0
7                                         0
8                                         0
9                                         1
10                                        0
11                                        0
12                                        0
13                                        1
14                                        0
15                                        0
16                                        1
17                                        0
18                                        0
19                                        0
20                                        0
21                                        0
22                                        1
23                                        0
24                                        1
25                                        0
26                                        0
27                                        0
28                                        0
29                                        0
...                                     ...
307481                                    0
307482                                    1
307483                                    0
307484                                    0
307485                                    0
307486                                    0
307487                                    0
307488                                    0
307489                                    0
307490                                    0
307491                                    0
307492                                    0
307493                                    0
307494                                    0
307495                                    0
307496                                    1
307497                                    1
307498                                    0
307499                                    0
307500                                    0
307501                                    0
307502                                    0
307503                                    0
307504                                    0
307505                                    0
307506                                    1
307507                                    0
307508                                    1
307509                                    0
307510                                    1

        WEEKDAY_APPR_PROCESS_START_TUESDAY  \
0                                        0
1                                        0
2                                        0
3                                        0
4                                        0
5                                        0
6                                        0
7                                        0
8                                        0
9                                        0
10                                       0
11                                       0
12                                       0
13                                       0
14                                       0
15                                       0
16                                       0
17                                       0
18                                       0
19                                       0
20                                       0
21                                       0
22                                       0
23                                       0
24                                       0
25                                       0
26                                       0
27                                       0
28                                       0
29                                       1
...                                    ...
307481                                   0
307482                                   0
307483                                   0
307484                                   0
307485                                   0
307486                                   0
307487                                   0
307488                                   0
307489                                   0
307490                                   0
307491                                   0
307492                                   0
307493                                   0
307494                                   0
307495                                   0
307496                                   0
307497                                   0
307498                                   0
307499                                   1
307500                                   0
307501                                   0
307502                                   0
307503                                   0
307504                                   0
307505                                   0
307506                                   0
307507                                   0
307508                                   0
307509                                   0
307510                                   0

        WEEKDAY_APPR_PROCESS_START_WEDNESDAY
0                                          1
1                                          0
2                                          0
3                                          1
4                                          0
5                                          1
6                                          0
7                                          0
8                                          1
9                                          0
10                                         0
11                                         0
12                                         0
13                                         0
14                                         0
15                                         0
16                                         0
17                                         0
18                                         0
19                                         0
20                                         0
21                                         0
22                                         0
23                                         0
24                                         0
25                                         0
26                                         0
27                                         0
28                                         1
29                                         0
...                                      ...
307481                                     0
307482                                     0
307483                                     0
307484                                     0
307485                                     0
307486                                     0
307487                                     1
307488                                     1
307489                                     0
307490                                     0
307491                                     0
307492                                     0
307493                                     0
307494                                     0
307495                                     1
307496                                     0
307497                                     0
307498                                     0
307499                                     0
307500                                     0
307501                                     1
307502                                     0
307503                                     0
307504                                     1
307505                                     0
307506                                     0
307507                                     0
307508                                     0
307509                                     1
307510                                     0

[307511 rows x 7 columns]

In [13]:
sub_train1.head()

,WEEKDAY_APPR_PROCESS_START_FRIDAY,WEEKDAY_APPR_PROCESS_START_MONDAY,WEEKDAY_APPR_PROCESS_START_SATURDAY,WEEKDAY_APPR_PROCESS_START_SUNDAY,WEEKDAY_APPR_PROCESS_START_THURSDAY,WEEKDAY_APPR_PROCESS_START_TUESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY
0,0,0,0,0,0,0,1
1,0,1,0,0,0,0,0
2,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1
4,0,0,0,0,1,0,0